apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mean-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
        version: v0.1
    spec:
      containers:
      - name: mean-pod
        image: wiwa1978/mean-todo-app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-server

