apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    type: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000
      protocol: TCP
  selector:
    type: web